cau-likelion-org/kiwi-client

- src/components/post/Post.tsx
> Feat: 이미지 경로 수정

- src/apis/history.ts
- src/app/docHistory/page.tsx
- src/components/docHistory/DocHistory.tsx
***
- 문서역사 변경사항 파싱
- api 호출 함수 추가
***
-'''app/docHistory''' : <요약 내용>
-'''apis/history''' : <요약 내용>
***
***
> [FEAT] 문서역사 파싱로직 추가 및 api 호출 함수 추가

- src/apis/docs.ts
- src/apis/types.ts
- src/components/landing/Landing.tsx
- src/components/post/MD.tsx
- src/components/post/Modal.tsx
***
- 문서 작성 및 최근 편집 목록 불러오기 구현
***
-'''docs.ts, Modal.tsx''' : API호출 코드 작성 및 타입 지정 후 BODY에 담아서 API 호출 코드 연결
***
***
> Feat: 문서 작성 및 최근 편집 목록 불러오기 구현

- src/apis/docs.ts
- src/components/post/MD.tsx
- tsconfig.json
> Feat: 이미지 업로드 구현

- src/apis/docs.ts
- src/components/post/MD.tsx
> Feat: 이미지 업로드 blob 객체 및 파일 객체를 담아서 호출

- src/apis/history.ts
- src/components/docHistory/DocHistory.tsx
***
- 문서역사 api 연동
***
***
- Resolved : #37
***
> [FEAT] 문서역사 api 연동

- src/components/landing/Landing.tsx
- src/components/landing/LandingSection1.tsx
***
- 랜딩 이미지 추가 
***
-'''Landing.tsx''' : <요약 내용>
***
- Resolved : #69 
***
> DESIGN: 랜딩 이미지 추가

- src/components/landing/Landing.tsx
- src/components/landing/LandingSection1.tsx
- src/components/landing/LandingSection2.tsx
- src/components/landing/LandingSection3.tsx
> FIX: 화면 줄였을 때 랜딩 작은 이미지들 제거거

- src/apis/docs.ts
- src/components/landing/Landing.tsx
- src/components/landing/LandingSection1.tsx
- src/components/landing/LandingSection2.tsx
- src/components/landing/LandingSection3.tsx
- src/components/userName/UserNickNameMain.tsx
> Feat: 랜딩 및 회원가입 디자인 수정 (#77)

- src/components/viewer/ViewerMain.tsx
- yarn.lock
> refactor: 뷰어-목차 없는 경우 오류 수정

- src/components/docHistory/DocHistory.tsx
***
- 문서역사 파싱 수정 (개행, 비동기로 인해 파싱 안되는 이슈 해결, 날짜 파싱)
***
***
***
> [FEAT] 문서역사 파싱 수정

- src/components/docHistory/DocHistory.tsx
> Develop : 문서 역사 부분 머지

- src/components/post/MD.tsx
> Feat: 라이브러리 에러 야매로 해결

- package-lock.json
- package.json
- src/components/viewer/ViewerMain.tsx
- yarn.lock
> refactor: 마크다운 수정

- src/components/edit/Editor.tsx
- src/components/post/MD.tsx
> Feat: 편집 및 작성 취소버튼 활성화

- src/components/viewer/ViewerMain.tsx
> fix: 콘솔 출력 삭제

- src/components/edit/Editor.tsx
- src/components/post/MD.tsx
> Feat: 에디터 배포 환경과 로컬 환경이 달라서 배포 환경으로 맞춤

- src/components/edit/Edit.tsx
- src/components/post/Post.tsx
> FIX: 스케치북 그림자 디테일 변경

- src/components/common/post/Modal.tsx
- src/types/request.d.ts
***
- author 타입 제거
***
***
***
> Feat: api 명세 수정에 맞게 body 타입 변경

- src/apis/viewer.ts
> FIX: GET요청 인코딩 URL로 변경

- src/components/edit/Editor.tsx
- src/components/post/MD.tsx
- src/components/viewer/ViewerMain.tsx
> FIX: 이미지 삽입 크기 퍼센트로 변경

- src/components/edit/Editor.tsx
- src/components/post/MD.tsx
- src/components/viewer/ViewerMain.tsx
> FIX: 이미지 크기 변경

- src/apis/sort.ts
- src/components/sort/Sort.tsx
- src/components/viewer/ViewerMain.tsx
> 분류 페이지 & 코드 블록 css

- src/apis/sort.ts
- src/components/sort/Sort.tsx
> design: sort 내용 안 겹치게  너비 수정

- src/app/layout.tsx
- src/app/search/page.tsx
- src/components/search/SearchBodySection.tsx
- src/components/search/SearchForm.tsx
- src/components/search/SearchFound.tsx
- src/components/search/SearchHeadSection.tsx
- src/components/search/SearchNotFound.tsx
- src/hooks/useSearchForm.ts
- yarn.lock
***
- 검색화면 반응형 디자인 추가 적용 및 디테일 수정
***
-'''Search''' 
***
- Resolved : #109 
***
> [DESIGN] 검색화면 반응형 디자인 추가 적용 및 디테일 수정

- .eslintrc.json
- package-lock.json
- package.json
- src/apis/docs.ts
- src/app/ReactQueryProvider.tsx
- src/app/layout.tsx
- src/components/search/AutoCompleteBox.tsx
- src/components/search/AutoCompleteContainer.tsx
- src/components/search/SearchBodySection.tsx
- src/components/search/SearchForm.tsx
- src/components/search/SearchFound.tsx
- src/components/search/SearchHeaderForm.tsx
- src/components/search/SearchNotFound.tsx
- src/components/search/SearchPageForm.tsx
- src/components/search/SearchResult.tsx
- src/hooks/useDebounce.ts
- src/hooks/useSearchAutoCompleteQuery.ts
- src/hooks/useSearchForm.ts
- src/hooks/useSearchQuery.ts
- src/types/request.d.ts
- src/types/search.d.ts
- yarn.lock
***
- react-query 도입하여 서버 상태 관리 (search)
- 검색 타입 구체화
- 검색 결과 캐싱하여 API 호출 감소
- package.json 의존성 수정
***
-'''components/search'''
***
- Resolved : #112 
***
> [REFACTOR] react-query 도입하여 서버 상태 관리 (search)

- src/components/docHistory/DocHistory.tsx
- src/hooks/useHistoryQuery.ts
- src/types/request.d.ts
- src/utils/historyUtils.ts
***
- react query로 문서역사 상태 관리
***
-'''src/hooks/useHistoryQuery''' : 
***
- Resolved : #115 
***
> [REFACTOR] react query로 문서역사 상태 관리

- src/components/docHistory/DocHistory.tsx
- src/hooks/useHistoryQuery.ts
> [CHORE] useHistoryQuery 코드 수정

- src/apis/viewer.ts
***
- 백엔드 배포 링크를 변경하면서, docs 부분에 변경되지 않았던 엔드포인트를 수정하였습니다
- //docs -> /docs
***
-'''apis/docs.ts''' : 엔드포인트 수정
> [FIX] docs 엔드포인트 수정
